import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import icon from '@/assets/favicon.ico'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
    icons: icon.src
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>{children}</body>
        </html>
    );
}
